# Generated by Django 5.2.7 on 2025-10-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_alter_customer_options_remove_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel Order")]},
        ),
    ]
