# Generated by Django 5.2.7 on 2025-10-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={
                "ordering": ["user__first_name", "user__last_name"],
                "permissions": [("view_history", "can view history")],
            },
        ),
    ]
